[package]
name = "ethereum_ssz"
version = "0.5.4"
edition = "2021"
description = "SimpleSerialize (SSZ) as used in Ethereum"
license = "Apache-2.0"
readme = "../README.md"
repository = "https://github.com/sigp/ethereum_ssz"
documentation = "https://docs.rs/ethereum_ssz"
keywords = ["ethereum"]
categories = ["cryptography::cryptocurrencies"]

[lib]
name = "ssz"

[dev-dependencies]
ethereum_ssz_derive = { version = "0.5.4", path = "../ssz_derive" }

[dependencies]
ethereum-types = "0.14.1"
ethereum_serde_utils = "0.5.0"
smallvec = { version = "1.6.1", features = ["const_generics"] }
itertools = "0.13.0"
serde = "1.0.0"
serde_derive = "1.0.0"
typenum = "1.12.0"
derivative = "2.1.1"
arbitrary = { version = "1.0", features = ["derive"], optional = true }

[features]
arbitrary = ["dep:arbitrary", "ethereum-types/arbitrary"]
